name: Build 1-Click Executables

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            executable: youtube-downloader-linux
          - os: windows-latest
            name: windows
            executable: youtube-downloader-windows.exe
            
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller -U --pre "yt-dlp[default]" flask flask-cors

    - name: Install Linux-only dependencies
      if: matrix.name == 'linux'
      run: pip install secretstorage

    - name: Build with PyInstaller (Linux)
      if: matrix.name == 'linux'
      run: |
        wget https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz
        tar -xf ffmpeg-master-latest-linux64-gpl.tar.xz
        cp ffmpeg-master-latest-linux64-gpl/bin/ffmpeg .
        pyinstaller --onefile --add-binary "ffmpeg:." --name ${{ matrix.executable }} server.py

    - name: Build with PyInstaller (Windows)
      if: matrix.name == 'windows'
      run: |
        curl -L -o ffmpeg.zip https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
        unzip -j ffmpeg.zip "ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe" -d .
        pyinstaller --onefile --add-binary "ffmpeg.exe:." --name ${{ matrix.executable }} server.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.executable }}
        path: dist/${{ matrix.executable }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'push'
    steps:
      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: youtube-downloader-windows.exe
          
      - name: Download Linux Build
        uses: actions/download-artifact@v4
        with:
          name: youtube-downloader-linux

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v2.1.${{ github.run_number }}"
          name: "Latest Auto-Build"
          files: |
            youtube-downloader-windows.exe
            youtube-downloader-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
